version: '3'

services:
  tests:
    image: ui_tests_opencart:latest
    volumes:
      - ./allure-results:/root/test/allure-results
    environment:
      - BROWSER=chrome
    command: ["--vnc", "--browser=${BROWSER}"]
    depends_on:
      - opencart
    networks:
      - selenoid

  phpadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=bn_opencart
    ports:
      - '${PHPADMIN_PORT}:80'
    networks:
      - selenoid

  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    ports:
      - '3306:3306'
    networks:
      - selenoid

  opencart:
    image: bitnami/opencart:4.0.2-3-debian-12-r33
    ports:
      - '${OPENCART_PORT}:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=${LOCAL_IP}:${OPENCART_PORT}
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - mariadb
    networks:
      - selenoid

networks:
  selenoid:
    external: true